#!/usr/bin/env bash

if [ -d ~/boxbox ]; then
  echo "[!] ~/boxbox directory exists"
  echo "[!] Box Box is already installed"
  echo "[!] Please remove it before you try to install it again"
  exit 1
fi

# -------------------------------------------------------------------------------------------------------------------------

echo "[*] Checking if git is installed"

if ! (which git > /dev/null); then
  echo "[!] Please install git"
fi

# -------------------------------------------------------------------------------------------------------------------------

echo "[*] Checking if wget is installed"

if ! (which wget > /dev/null); then
  echo "[!] Please install wget"
else
  brew install wget
fi

# -------------------------------------------------------------------------------------------------------------------------

echo "[*] Checking if Virtual Box is available"

if which vboxmanage > /dev/null; then
  version=$(vboxmanage --version)

  echo "[*] Virtual Box found: $version"
else
  echo "[*] Installing Virtual Box"

  brew cask install virtualbox
fi

# -------------------------------------------------------------------------------------------------------------------------

echo "[*] Checking if Vagrant is available"

if which vagrant> /dev/null; then
  version=$(vagrant --version)

  echo "[*] Vagrant found: $version"
else
  echo "[*] Installing Vagrant"

  brew cask install vagrant
fi

# -------------------------------------------------------------------------------------------------------------------------

echo "[*] Installing vagrant hostmanager"

vagrant plugin install vagrant-hostmanager

# -------------------------------------------------------------------------------------------------------------------------

echo "[*] Cloning boxbox from GitHub"

git clone https://github.com/shiroyasha/boxbox.git ~/boxbox
cd ~/boxbox

echo "[*] Provisioning your boxbox"
vagrant up

if [ $SHELL == "/bin/zsh" ]; then
  shell_filepath=~/.zshrc
else
  shell_filepath=~/.bash_profile
fi

echo "[*] Setting up aliases in $shell_filepath"
echo 'alias bb="cd ~/boxbox && vagrant up && vagrant ssh"' >> $shell_filepath
echo 'alias bhalt="cd ~/boxbox && vagrant halt"' >> $shell_filepath

echo "[*] Done"
echo ""
echo "Type 'bb' to start using your boxbox machine"
